// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>
#include "arduino_secrets.h"

const char DEVICE_LOGIN_NAME[]  = "8b38b30c-2ee9-42fe-b24b-f8c953cd426c";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]         = SECRET_DEVICE_KEY;    // Secret device password

void onStokChange();
void onFeedChange();
void onFeedingSecondChange();
void onJadwalDuaChange();
void onJadwalSatuChange();

float stok;
bool feed;
CloudTime feeding_second;
CloudTime jadwal_dua;
CloudTime jadwal_satu;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(stok, READWRITE, ON_CHANGE, onStokChange);
  ArduinoCloud.addProperty(feed, READWRITE, ON_CHANGE, onFeedChange);
  ArduinoCloud.addProperty(feeding_second, READWRITE, ON_CHANGE, onFeedingSecondChange);
  ArduinoCloud.addProperty(jadwal_dua, READWRITE, ON_CHANGE, onJadwalDuaChange);
  ArduinoCloud.addProperty(jadwal_satu, READWRITE, ON_CHANGE, onJadwalSatuChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection("", "");
// WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
